{"name": "Тест на возврат ошибки при cоздании зарегистрированного пользователя", "status": "passed", "steps": [{"name": "Регистрация пользователя", "status": "passed", "start": 1745514870559, "stop": 1745514870742}], "start": 1745514870559, "stop": 1745514870742, "uuid": "448fbc36-a606-4b50-af09-5f1eff6af4e9", "historyId": "dc6047c380b5abb6ca4f3938b79057d4", "testCaseId": "dc6047c380b5abb6ca4f3938b79057d4", "fullName": "tests.test_register_user.TestCreateUser#test_re_register_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_register_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "WIN-81M7B7JCB93"}, {"name": "thread", "value": "3120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_register_user"}]}